### PR TITLE
insertionSort Algorithm

### PR DESCRIPTION
**Pull request by william-monroy**
The pull request includes only the code of the algorithm that was assigned to us so that the other collaborating members of the issue can contribute to the other two pending items. issue #16

### CODE REVIEW

**Review by ST1LLWATER — CHANGES_REQUESTED** [review]
No Information About the algorithm, complexity provided

**Comment by william-monroy** [comment]
I add the information of the algorithm, time complexity, and space complexity for issues #16 and #17

**Review by ST1LLWATER — CHANGES_REQUESTED** [review]
Insertion Sort Can be made O(n) in best case scenario

**Comment by william-monroy** [comment]
@ST1LLWATER I add Time complexity algorithms: best, average, and worst.

**Comment by william-monroy** [comment]
@ST1LLWATER The corrections cover issues #16 and #17

**Review by ST1LLWATER — APPROVED** [review]
Checked And Approved

**Pull request merged**
