### PR TITLE
Added solution for issue no #21

### PR DESCRIPTION
**Pull request by SugatoBagchi**
Added solution for issue no #21

### CODE REVIEW

**Review by ST1LLWATER — CHANGES_REQUESTED** [review]
No Additional information about the algorithm and complexity provided.

**Comment by SugatoBagchi** [comment]
on it

**Comment by SugatoBagchi** [comment]
Let me know if you need any more details.

**Comment by ST1LLWATER** [comment]
Wasnt merged due to multiple PRs for same issue simultaneously so i had to select one that time. Ill create more issues keep following if you want to contribute later. @SugatoBagchi

**Pull request closed without merging**
