### PR TITLE
Resolved issue #90

### PR DESCRIPTION
**Pull request by ayeshatahirme**
Added an algorithm that was not in the repo before.

### CODE REVIEW

**Comment by ST1LLWATER** [comment]
Good Work :)

**Comment by ayeshatahirme** [comment]
please do add "hackoberfest-accepted" label

**Comment by ST1LLWATER** [comment]
np ill add it, its not necessary though a valid merge in a hacktoberfest repo counts as a contribution. Anyways ill add it.

**Comment by ayeshatahirme** [comment]
So kind of you. Thanks :)

**Pull request merged**
